### ISSUE TITLE
Connecting to multiple databases

### ISSUE THREAD

**Issue by chugunov** [elixir-mongo/mongodb#100]
I need to create connections to two different databases in my supervisor tree.
```
def start(_type, _args) do
  import Supervisor.Spec

  children = [
    worker(Mongo, [[name: :repone, database: "database-one", pool: DBConnection.Poolboy]]),
    worker(Mongo, [[name: :reptwo, database: "database-two", pool: DBConnection.Poolboy]])
  ]

  opts = [strategy: :one_for_one, name: MyApp.Supervisor]
  Supervisor.start_link(children, opts)
end
```
But when I try to run application, it crashes.
```
** (Mix) Could not start application keys: exited in: Keys.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) duplicated id Mongo found in the supervisor specification, please explicitly pass the :id option when defining this worker/supervisor
            (elixir) lib/supervisor/spec.ex:175: Supervisor.Spec.assert_unique_ids/1
            (elixir) lib/supervisor/spec.ex:169: Supervisor.Spec.supervise/2
            (elixir) lib/supervisor.ex:284: Supervisor.start_link/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

I could create two connections in previous version like [this](https://github.com/ericmj/mongodb/issues/42#issuecomment-178560775), but I have no idea how to do that now. Does exist any walkthrough in my case?

**Comment by ericmj** [comment]
I think the error message explains what to do? You need to add a unique `:id` key to the `worker` options.

**Comment by chugunov** [comment]
Oh, I'm a newbie in Elixir, sorry. @ericmj thank you for the fast response.
