### ISSUE TITLE
Error using Poolboy

### ISSUE THREAD

**Issue by matreyes** [elixir-mongo/mongodb#134]
Hi.. 
I'm trying to connect with poolboy 
```
worker(Mongo, [[database: Application.get_env(:may_app, :db)[:name], name: :my_app, pool: DBConnection.Poolboy]])
```
and it raises with any call (find_one, insert_one, delete_many)

```
 ** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
     stacktrace:
       :invalid_message.exception([])
       (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
       (db_connection) lib/db_connection.ex:742: DBConnection.run/3
       (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
       (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
       (mongodb) lib/mongo.ex:582: Mongo.delete_many/4
       test/db/mongo_test.exs:5: Db.MongoTest.__ex_unit_setup_0/1
       test/db/mongo_test.exs:1: Db.MongoTest.__ex_unit__/2
```
I'm using:
```
* poolboy 1.5.1 (Hex package) (rebar)
* db_connection 1.1.2 (Hex package) (mix)
* mongodb 0.4.0 (Hex package) (mix)
```
Removing Poolboy, it works great!

Best

**Comment by matreyes** [comment]
Oh... no....
I have to use `pool: DBConnection.Poolboy` on every call! 
I'm sorry!

Do you have any idea to avoid the boilerplate?

**Comment by ankhers** [comment]
I can only think of two options to remove the boilerplate.

* Wrap the functions provided by this driver in your own functions
* Try using the [`mongodb_ecto`](https://github.com/michalmuskala/mongodb_ecto/) package
