### ISSUE TITLE
A single mongo node being brought down will crash the entire app

### ISSUE THREAD

**Issue by ben-ic** [elixir-mongo/mongodb#142]
If you are using mongodb replica set and one node becomes unavailable the entire mongodb driver will crash ultimately crashing the entire app.

**Comment by ankhers** [comment]
So this was actually a misfeature of the `db_connection` package. This has been resolved in master and will released with v1.1. Unfortunately I do not know when it will actually be released. 

I have offered to help expedite the process, so I am hoping to have my portion of that work done over the weekend.

**Comment by christianjgreen** [comment]
Isn't `db_connection` already on 1.1.2 as of march?

**Comment by ankhers** [comment]
You are right. I missed that originally. However, the rest of what I said is still true. The issue has been fixed on master and will be released hopefully somewhat shortly.

**Comment by christianjgreen** [comment]
Just brought in master branch of `db_connection` and still had the application shutdown after one of the 3 secondary nodes in the replica set went down.

**Comment by ankhers** [comment]
Can you please post the error you received?

**Comment by christianjgreen** [comment]
The majority of the errors were
```
 (CaseClauseError) no case clause matching: {:error, %DBConnection.ConnectionError{message: "connection not available because of disconnection"}}
    (mongodb) lib/mongo/monitor.ex:94: Mongo.Monitor.is_master/3
    (mongodb) lib/mongo/monitor.ex:70: Mongo.Monitor.check/1
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.588.0>, {{:case_clause, {:error, %DBConnection.ConnectionError{message: "connection not available because of disconnection"}}}, [{Mongo.Monitor, :is_master, 3, [file: 'lib/mongo/monitor.ex', line: 94]}, {Mongo.Monitor, :check, 1, [file: 'lib/mongo/monitor.ex', line: 70]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 601]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 667]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: {:state, #PID<0.620.0>, [#PID<0.630.0>, #PID<0.629.0>, #PID<0.628.0>, #PID<0.627.0>, #PID<0.626.0>, #PID<0.625.0>, #PID<0.624.0>, #PID<0.623.0>, #PID<0.622.0>, #PID<0.621.0>], {[], []}, 200763, 10, 0, 0, :fifo}
[error] GenServer #PID<0.605.0> terminating
** (CaseClauseError) no case clause matching: {:error, %DBConnection.ConnectionError{message: "connection not available because of disconnection"}}
    (mongodb) lib/mongo/monitor.ex:94: Mongo.Monitor.is_master/3
    (mongodb) lib/mongo/monitor.ex:70: Mongo.Monitor.check/1
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.588.0>, {{:case_clause, {:error, %DBConnection.ConnectionError{message: "connection not available because of disconnection"}}}, [{Mongo.Monitor, :is_master, 3, [file: 'lib/mongo/monitor.ex', line: 94]}, {Mongo.Monitor, :check, 1, [file: 'lib/mongo/monitor.ex', line: 70]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 601]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 667]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: {:state, #PID<0.606.0>, [#PID<0.616.0>, #PID<0.615.0>, #PID<0.614.0>, #PID<0.613.0>, #PID<0.612.0>, #PID<0.611.0>, #PID<0.610.0>, #PID<0.609.0>, #PID<0.608.0>, #PID<0.607.0>], {[], []}, 196672, 10, 0, 0, :fifo}
```

**Comment by ankhers** [comment]
(Un)fortunately that is actually an issue with this driver. We are attempting to match what `db_connection` returns (`{:error, reason_exception}`) with `{:disconnect, reason, _?}`. This issue has actually been fixed in my `reboot_replica_sets` branch. However, there is still more work to be done on it.
