### ISSUE TITLE
Need support for Atlas Free Tier

### ISSUE THREAD

**Issue by suprafly** [elixir-mongo/mongodb#154]
I have opened a free tier Atlas account. I have the connection string.

I am able to connect to Mongo via shell, however when attempting to connect vid the mongodb driver I get this:

_(I have removes the seed string and credentials)_
```
Mongo.start_link(seeds: ["host strings"], ssl: true, database: "test", username: "SOMEUSER", password: "SOMEPASSWORD", port: 27017, type: "replica_set_primary")
{:ok, #PID<0.172.0>}

** (EXIT from #PID<0.683.0>) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-01-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.21209>, :tls_connection, :undefined}, #PID<0.696.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.688.0>, wire_version: nil, write_concern: %{w: 1}}}
        (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
        
16:30:45.720 [error] GenServer #PID<0.692.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-01-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.21209>, :tls_connection, :undefined}, #PID<0.696.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.688.0>, wire_version: nil, write_concern: %{w: 1}}}
    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol

16:30:45.720 [error] GenServer #PID<0.690.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-00-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.21208>, :tls_connection, :undefined}, #PID<0.698.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.688.0>, wire_version: nil, write_concern: %{w: 1}}}
    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol

16:30:45.721 [error] GenServer #PID<0.694.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.21210>, :tls_connection, :undefined}, #PID<0.697.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.688.0>, wire_version: nil, write_concern: %{w: 1}}}
    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol
```

I am wondering how I can resolve this issue?

**Comment by ankhers** [comment]
This has been fixed on master. Would you be able to test to ensure it is working correctly for you?

**Comment by suprafly** [comment]
Still seeing the same errors when I run the same command:

```
** (EXIT from #PID<0.169.0>) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.6398>, :tls_connection, :undefined}, #PID<0.183.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.172.0>, wire_version: nil, write_concern: %{w: 1}}}
        (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
        
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(3)> 
09:37:46.181 [error] GenServer #PID<0.176.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-01-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.6399>, :tls_connection, :undefined}, #PID<0.182.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.172.0>, wire_version: nil, write_concern: %{w: 1}}}
    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol
iex(1)> 
09:37:46.181 [error] GenServer #PID<0.178.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.6398>, :tls_connection, :undefined}, #PID<0.183.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.172.0>, wire_version: nil, write_concern: %{w: 1}}}
    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol

09:37:46.182 [error] GenServer #PID<0.174.0> terminating
** (CaseClauseError) no case clause matching: {:disconnect, %Mongo.Error{code: 8000, message: "no SNI name sent, make sure using a MongoDB 3.4+ driver/shell."}, %{connection_type: :monitor, database: "admin", host: "cluster0-shard-00-00-ao6j6.mongodb.net:27017", request_id: 0, socket: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.6397>, :tls_connection, :undefined}, #PID<0.181.0>}}, ssl: true, timeout: 5000, topology_pid: #PID<0.172.0>, wire_version: nil, write_concern: %{w: 1}}}
    (mongodb) lib/mongo/protocol.ex:54: Mongo.Protocol.connect/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol
```

**Comment by suprafly** [comment]
Linked to the master branch of your repo like so:
```
  defp deps do
    [      
      {:mongodb, github: "ankhers/mongodb", branch: "master"},
    ]
  end
```

And now running the above command produces these errors:
```
** (EXIT from #PID<0.489.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.TopologyDescription.update_topology/4
        (mongodb) lib/mongo/topology_description.ex:269: Mongo.TopologyDescription.update_topology(%{compatibility_error: nil, compatible: true, local_threshold_ms: 15, max_election_id: nil, max_set_version: nil, servers: %{"REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "REMOVED", "REMOVED"], last_update_time: -576460731538, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 16, microsecond: {0, 3}, minute: 49, month: 9, second: 45, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462708522323804192>}, passives: [], primary: "REMOVED", round_trip_time: 461, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, "REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}}, set_name: nil, type: "replica_set_primary"}, "replica_set_primary", %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "REMOVED", "REMOVED"], last_update_time: -576460731538, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 16, microsecond: {0, 3}, minute: 49, month: 9, second: 45, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462708522323804192>}, passives: [], primary: "REMOVED", round_trip_time: 461, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, 3)
        (mongodb) lib/mongo/topology_description.ex:262: Mongo.TopologyDescription.check_server_in_topology/3
        (elixir) lib/map.ex:694: Map.get_and_update/3
        (mongodb) lib/mongo/topology.ex:166: Mongo.Topology.handle_server_description/2
        (mongodb) lib/mongo/topology.ex:119: Mongo.Topology.handle_call/3
        (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
        
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
09:49:45.243 [error] GenServer #PID<0.496.0> terminating
** (FunctionClauseError) no function clause matching in Mongo.TopologyDescription.update_topology/4
    (mongodb) lib/mongo/topology_description.ex:269: Mongo.TopologyDescription.update_topology(%{compatibility_error: nil, compatible: true, local_threshold_ms: 15, max_election_id: nil, max_set_version: nil, servers: %{"REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "REMOVED", "REMOVED"], last_update_time: -576460731538, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 16, microsecond: {0, 3}, minute: 49, month: 9, second: 45, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462708522323804192>}, passives: [], primary: "REMOVED", round_trip_time: 461, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, "REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}}, set_name: nil, type: "replica_set_primary"}, "replica_set_primary", %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "REMOVED", "REMOVED"], last_update_time: -576460731538, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 16, microsecond: {0, 3}, minute: 49, month: 9, second: 45, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462708522323804192>}, passives: [], primary: "REMOVED", round_trip_time: 461, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, 3)
    (mongodb) lib/mongo/topology_description.ex:262: Mongo.TopologyDescription.check_server_in_topology/3
    (elixir) lib/map.ex:694: Map.get_and_update/3
    (mongodb) lib/mongo/topology.ex:166: Mongo.Topology.handle_server_description/2
    (mongodb) lib/mongo/topology.ex:119: Mongo.Topology.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:server_description, %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "REMOVED", "REMOVED"], last_update_time: -576460731538, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 16, microsecond: {0, 3}, minute: 49, month: 9, second: 45, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462708522323804192>}, passives: [], primary: "REMOVED", round_trip_time: 461, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}}
State: %{connection_pools: %{"REMOVED" => #PID<0.510.0>, "REMOVED" => #PID<0.508.0>, "REMOVED" => #PID<0.512.0>}, monitors: %{"REMOVED" => #PID<0.497.0>, "REMOVED" => #PID<0.499.0>, "REMOVED" => #PID<0.501.0>}, opts: [seeds: ["REMOVED", "REMOVED", "REMOVED"], ssl: true, database: "test", username: "REMOVED", password: "REMOVED", port: 27017, type: "replica_set_primary"], seeds: ["REMOVED", "REMOVED", "REMOVED"], topology: %{compatibility_error: nil, compatible: true, local_threshold_ms: 15, max_election_id: nil, max_set_version: nil, servers: %{"REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}}, set_name: nil, type: "replica_set_primary"}}
```

**Comment by suprafly** [comment]
@ankhers if you want to borrow our creds to test it out yourself, would be happy to share them - we just need to touch base off of this thread to exchange them. You can message me in the Elixir Slack chat, `@suprafly`

**Comment by ankhers** [comment]
That is because you are using `type: "replica_set_primary"`. That is not a valid value for that option. You are going to want to either not set it, or set it to one of `:unknown`, `:single`, `:replica_set_no_primary` or `:sharded`. Note that these are atoms, not strings.

**Comment by suprafly** [comment]
With atoms, I get this error:
```
** (EXIT from #PID<0.540.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.TopologyDescription.update_topology/4
        (mongodb) lib/mongo/topology_description.ex:269: Mongo.TopologyDescription.update_topology(%{compatibility_error: nil, compatible: true, local_threshold_ms: 15, max_election_id: nil, max_set_version: nil, servers: %{"REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], last_update_time: -576459748344, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 17, microsecond: {0, 3}, minute: 6, month: 9, second: 7, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462712739981688836>}, passives: [], primary: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", round_trip_time: 456, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, "cluster0-shard-00-01-ao6j6.mongodb.net:27017" => %{address: "cluster0-shard-00-01-ao6j6.mongodb.net:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "cluster0-shard-00-02-ao6j6.mongodb.net:27017" => %{address: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}}, set_name: nil, type: :replica_set_primary}, :replica_set_primary, %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], last_update_time: -576459748344, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 17, microsecond: {0, 3}, minute: 6, month: 9, second: 7, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462712739981688836>}, passives: [], primary: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", round_trip_time: 456, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, 3)
        (mongodb) lib/mongo/topology_description.ex:262: Mongo.TopologyDescription.check_server_in_topology/3
        (elixir) lib/map.ex:694: Map.get_and_update/3
        (mongodb) lib/mongo/topology.ex:166: Mongo.Topology.handle_server_description/2
        (mongodb) lib/mongo/topology.ex:119: Mongo.Topology.handle_call/3
        (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
        
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(5)> 
10:06:08.427 [error] GenServer #PID<0.545.0> terminating
** (FunctionClauseError) no function clause matching in Mongo.TopologyDescription.update_topology/4
    (mongodb) lib/mongo/topology_description.ex:269: Mongo.TopologyDescription.update_topology(%{compatibility_error: nil, compatible: true, local_threshold_ms: 15, max_election_id: nil, max_set_version: nil, servers: %{"REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], last_update_time: -576459748344, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 17, microsecond: {0, 3}, minute: 6, month: 9, second: 7, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462712739981688836>}, passives: [], primary: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", round_trip_time: 456, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, "cluster0-shard-00-01-ao6j6.mongodb.net:27017" => %{address: "cluster0-shard-00-01-ao6j6.mongodb.net:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "cluster0-shard-00-02-ao6j6.mongodb.net:27017" => %{address: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}}, set_name: nil, type: :replica_set_primary}, :replica_set_primary, %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], last_update_time: -576459748344, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 17, microsecond: {0, 3}, minute: 6, month: 9, second: 7, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462712739981688836>}, passives: [], primary: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", round_trip_time: 456, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}, 3)
    (mongodb) lib/mongo/topology_description.ex:262: Mongo.TopologyDescription.check_server_in_topology/3
    (elixir) lib/map.ex:694: Map.get_and_update/3
    (mongodb) lib/mongo/topology.ex:166: Mongo.Topology.handle_server_description/2
    (mongodb) lib/mongo/topology.ex:119: Mongo.Topology.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:server_description, %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], last_update_time: -576459748344, last_write_date: %DateTime{calendar: Calendar.ISO, day: 6, hour: 17, microsecond: {0, 3}, minute: 6, month: 9, second: 7, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2017, zone_abbr: "UTC"}, max_wire_version: 5, me: "REMOVED", min_wire_version: 0, op_time: %{"t" => 8, "ts" => #BSON.Timestamp<6462712739981688836>}, passives: [], primary: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", round_trip_time: 456, set_name: "REMOVED", set_version: 1, tag_set: %{}, type: :rs_secondary}}
State: %{connection_pools: %{"REMOVED" => #PID<0.557.0>, "cluster0-shard-00-01-ao6j6.mongodb.net:27017" => #PID<0.559.0>, "cluster0-shard-00-02-ao6j6.mongodb.net:27017" => #PID<0.561.0>}, monitors: %{"REMOVED" => #PID<0.546.0>, "cluster0-shard-00-01-ao6j6.mongodb.net:27017" => #PID<0.548.0>, "cluster0-shard-00-02-ao6j6.mongodb.net:27017" => #PID<0.550.0>}, opts: [seeds: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], ssl: true, database: "test", username: "REMOVED", password: "REMOVED", port: 27017, type: :replica_set_primary], seeds: ["REMOVED", "cluster0-shard-00-01-ao6j6.mongodb.net:27017", "cluster0-shard-00-02-ao6j6.mongodb.net:27017"], topology: %{compatibility_error: nil, compatible: true, local_threshold_ms: 15, max_election_id: nil, max_set_version: nil, servers: %{"REMOVED" => %{address: "REMOVED", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "cluster0-shard-00-01-ao6j6.mongodb.net:27017" => %{address: "cluster0-shard-00-01-ao6j6.mongodb.net:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}, "cluster0-shard-00-02-ao6j6.mongodb.net:27017" => %{address: "cluster0-shard-00-02-ao6j6.mongodb.net:27017", arbiters: [], election_id: nil, error: nil, hosts: [], last_update_time: 0, last_write_date: nil, max_wire_version: 0, me: nil, min_wire_version: 0, op_time: nil, passives: [], primary: nil, round_trip_time: nil, set_name: nil, set_version: nil, tag_set: %{}, type: :unknown}}, set_name: nil, type: :replica_set_primary}}
```

**Comment by ankhers** [comment]
Because `:replica_set_primary` is not one of the values I told you was valid. I think you meant to write `:replica_set_no_primary`.

**Comment by suprafly** [comment]
Getting closer now. Fixed the atom problem, and now I only get this (repeatedly):
```
10:13:15.559 [error] Mongo.Protocol (#PID<0.190.0>) failed to connect: ** (Mongo.Error) auth failed for user REMOVED: Authentication failed. 8000

10:13:15.559 [error] Mongo.Protocol (#PID<0.192.0>) failed to connect: ** (Mongo.Error) auth failed for user REMOVED: Authentication failed. 8000

10:13:15.560 [error] Mongo.Protocol (#PID<0.189.0>) failed to connect: ** (Mongo.Error) auth failed for user REMOVED: Authentication failed. 8000
```

**Comment by suprafly** [comment]
Sidebar: that `:type` opt and those possible values are not documented https://hexdocs.pm/mongodb/0.4.0/Mongo.html#start_link/1

**Comment by ankhers** [comment]
Unfortunately it is documented elsewhere. But yes, it should be documented there instead of where it is.

You are going to want to use the `:auth_source` option.

**Comment by suprafly** [comment]
Great, when I add the `:auth_source` it works. Thanks for all your help resolving and getting working in this issue. If I can help you improve your documentation for this I would be glad to send a pull request. Just let me know.

**Comment by ankhers** [comment]
@suprafly If you want to help with documentation, feel free to look at the issue tracker. There are a couple issues labelled with the documentation tag.

**Comment by MarkNijhof** [comment]
I had the failed to connect issue as well and that was because I missed ssl: true as an config option. The mongo shell uses SSL but mongodb has it off by default
