### ISSUE TITLE
Unable to query oplog

### ISSUE THREAD

**Issue by jocko** [elixir-mongo/mongodb#18]
I'm getting an error running queries against the oplog on a MongoDB replica set. MongoDB v 2.6.5 / Elixir 1.0.5.

An iex session that illustrates this:

```
-> % iex -S mix
Erlang/OTP 18 [erts-7.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule MongoPool do use Mongo.Pool, name: __MODULE__, adapter: Mongo.Pool.Poolboy end                        {:module, MongoPool,
 <<70, 79, 82, 49, 0, 0, 9, 80, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 1, 111, 131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115, 95, 118, 49, 108, 0, 0, 0, 2, 104, 2, ...>>,
 :ok}
iex(2)> {:ok, _} = MongoPool.start_link(database: "local")
{:ok, #PID<0.134.0>}
iex(3)> Mongo.find(MongoPool, "oplog.rs", %{}) |> Enum.take(1)
** (exit) exited in: GenServer.call(#PID<0.150.0>, {:find, "oplog.rs", %{}, nil, [batch_size: 1000]}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Mongo.Connection.handle_info/2
            lib/mongo/connection.ex:346: Mongo.Connection.handle_info({:tcp, #Port<0.5509>, <<0, 3, 0, 0, 0, 82, 85, 0, 2, 49, 56, 48, 0, 3, 0, 0, 0, 82, 87, 0, 2, 49, 56, 49, 0, 3, 0, 0, 0, 82, 69, 0, 2, 49, 56, 50, 0, 3, 0, 0, 0, 66, 76, 0, 2, 49, 56, 51, ...>>}, {:ok, %{auth: [], database: "local", opts: [backoff: 1000, port: 27017, hostname: 'localhost'], queue: %{0 => %{command: :find, from: {#PID<0.127.0>, #Reference<0.0.3.911>}, params: nil}}, request_id: 1, socket: #Port<0.5509>, tail: <<84, 120, 47, 0, 85, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 138, 133, 8, 97, 208, 0, 0, 0, 0, 0, 0, 0, 232, 3, 0, 0, 242, 11, 0, 0, 17, 116, ...>>, timeout: 5000, wire_version: 2, write_concern: [w: 1]}})
            lib/connection.ex:798: Connection.handle_async/3
            (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3

18:55:47.367 [error] GenServer #PID<0.150.0> terminating
Last message: {:tcp, #Port<0.5509>, <<0, 3, 0, 0, 0, 82, 85, 0, 2, 49, 56, 48, 0, 3, 0, 0, 0, 82, 87, 0, 2, 49, 56, 49, 0, 3, 0, 0, 0, 82, 69, 0, 2, 49, 56, 50, 0, 3, 0, 0, 0, 66, 76, 0, 2, 49, 56, 51, ...>>}
State: {:ok, %{auth: [], database: "local", opts: [backoff: 1000, port: 27017, hostname: 'localhost'], queue: %{0 => %{command: :find, from: {#PID<0.127.0>, #Reference<0.0.3.911>}, params: nil}}, request_id: 1, socket: #Port<0.5509>, tail: <<84, 120, 47, 0, 85, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 138, 133, 8, 97, 208, 0, 0, 0, 0, 0, 0, 0, 232, 3, 0, 0, 242, 11, 0, 0, 17, 116, ...>>, timeout: 5000, wire_version: 2, write_concern: [w: 1]}}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.Connection.handle_info/2
        lib/mongo/connection.ex:346: Mongo.Connection.handle_info({:tcp, #Port<0.5509>, <<0, 3, 0, 0, 0, 82, 85, 0, 2, 49, 56, 48, 0, 3, 0, 0, 0, 82, 87, 0, 2, 49, 56, 49, 0, 3, 0, 0, 0, 82, 69, 0, 2, 49, 56, 50, 0, 3, 0, 0, 0, 66, 76, 0, 2, 49, 56, 51, ...>>}, {:ok, %{auth: [], database: "local", opts: [backoff: 1000, port: 27017, hostname: 'localhost'], queue: %{0 => %{command: :find, from: {#PID<0.127.0>, #Reference<0.0.3.911>}, params: nil}}, request_id: 1, socket: #Port<0.5509>, tail: <<84, 120, 47, 0, 85, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 138, 133, 8, 97, 208, 0, 0, 0, 0, 0, 0, 0, 232, 3, 0, 0, 242, 11, 0, 0, 17, 116, ...>>, timeout: 5000, wire_version: 2, write_concern: [w: 1]}})
        lib/connection.ex:798: Connection.handle_async/3
        (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (stdlib) timer.erl:181: :timer.tc/2
             lib/mongo/pool/poolboy.ex:34: Mongo.Pool.Poolboy.run/2
             lib/mongo/pool.ex:140: Mongo.Pool.run_with_log/5
             lib/mongo/cursor.ex:33: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
    (elixir) lib/stream.ex:1014: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:1740: Enum.take/2
```

**Comment by ericmj** [comment]
Thanks for the report.
