### ISSUE TITLE
Can't get it to work -  (UndefinedFunctionError) function :invalid_message.exception/1 is undefined

### ISSUE THREAD

**Issue by dmarko484** [elixir-mongo/mongodb#186]
I have Mongo defined under supervisor based on docs. Now any operation (Mongo.find, Mongod.insert_one etc. ) raises the same error as below. Any idea whats wrong here? (Elixir 1.5.3 on windows)

```
iex(web@127.0.0.1)3> cursor = Mongo.find(:mongo, "names", %{})
%Mongo.Cursor{coll: "names", conn: #PID<0.468.0>, opts: [slave_ok: true],
 query: %{}, select: nil}
iex(web@127.0.0.1)4> Enum.to_list(cursor)                     
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
    (mongodb) lib/mongo.ex:413: Mongo.raw_find/5
    (mongodb) lib/mongo/cursor.ex:40: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
    (elixir) lib/stream.ex:1270: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:1841: Enum.reverse/1
    (elixir) lib/enum.ex:2599: Enum.to_list/1

```

**Comment by ankhers** [comment]
Can you please show the supervisor where you are starting mongo?

**Comment by dmarko484** [comment]
```
defmodule Web.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the endpoint when the application starts
      supervisor(WebWeb.Endpoint, []),
      worker(Mongo, [[name: :mongo, database: "elixir_ph3", pool: DBConnection.Poolboy, hostname: "localhost"]]),

      # Start your own worker by calling: Web.Worker.start_link(arg1, arg2, arg3)
      # worker(Web.Worker, [arg1, arg2, arg3]),
    here it is ...

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Web.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    WebWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

**Comment by dmarko484** [comment]
And here is a traceback when I start Mongo in iex. using

>  {:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/elixir_ph3")

```
iex(web@127.0.0.1)1> {:ok, conn} = Mongo.start_link(url: "mongodb://localhost:27017/elixir_ph3")
{:ok, #PID<0.602.0>}
** (EXIT from #PID<0.600.0>) evaluator process exited with reason: an exception was raised:
    ** (KeyError) key :database not found in: [topology_pid: #PID<0.602.0>, connection_type: :client, url: "mongodb://localhost:27017/elixir_ph3", hostname: "localhost", port: 27017]
        (elixir) lib/keyword.ex:371: Keyword.fetch!/2
        (mongodb) lib/mongo/protocol.ex:30: Mongo.Protocol.connect/1
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
                     
Interactive Elixir (1.5.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(web@127.0.0.1)2> [error] GenServer #PID<0.609.0> terminating
** (KeyError) key :database not found in: [topology_pid: #PID<0.602.0>, connection_type: :client, url: "mongodb://localhost:27017/elixir_ph3", hostname: "localhost", port: 27017]
    (elixir) lib/keyword.ex:371: Keyword.fetch!/2
    (mongodb) lib/mongo/protocol.ex:30: Mongo.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol
```

**Comment by ankhers** [comment]
The `:url` key is only available on the master branch. Are you using master, or are you using the latest released version (0.4.3)?

**Comment by ankhers** [comment]
You have a mismatch on which pooling mechanism you are trying to use. You are starting this driver with `pool: DBConnection.Poolboy`, but when you are querying, you are not telling the query to use that pooling mechanism. You will need to query like `Mongo.find(pid, "collection", %{}, pool: DBConnection.Poolboy)`

#175 is a conversation surrounding this issue.

**Comment by dmarko484** [comment]
Ok, specifying pool did the trick ... thanks

**Comment by nitinjain1105** [comment]
Hi There,

I am trying to send data from my elixir application to mongodb. Following is the sequence of command I am running:

{:ok, conn} = Mongo.start_link(hostname: "localhost", database: "test", pool: DBConnection.Poolboy)
Mongo.find(conn, "collection", %{}, pool: DBConnection.Poolboy)
Mongo.insert_one(pid, "collection", %{foo: 42})

** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:934: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:750: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1141: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:644: DBConnection.execute/4
    (mongodb) lib/mongo.ex:519: Mongo.insert_one/4


Please Help
