### ISSUE TITLE
Access UpdateResult parameters

### ISSUE THREAD

**Issue by wu3rstle** [elixir-mongo/mongodb#195]
I want to return specific values from an UpdateResult.

Therefore i use the following code:

```elixir
{:ok, result} = Mongo.update_many :mongo, "articles", %{}, %{"$set": %{"imports.kqpri": false}}, pool: DBConnection.Poolboy
IO.puts "Updated #{result[:modified_count]} of #{result[:matched_count]} documents"
```

Executing this lines i get the following error:

```shell
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Mongo.UpdateResult.fetch/2 is undefined (Mongo.UpdateResult does not implement the Access behaviour)
        (mongodb) Mongo.UpdateResult.fetch(%Mongo.UpdateResult{matched_count: 599, modified_count: 599, upserted_id: nil}, :modified_count)
        (elixir) lib/access.ex:304: Access.get/3
        (articles) lib/articles_web/controllers/page_controller.ex:104: ArticlesWeb.PageController.update/2
        (articles) lib/articles_web/controllers/page_controller.ex:1: ArticlesWeb.PageController.action/2
        (articles) lib/articles_web/controllers/page_controller.ex:1: ArticlesWeb.PageController.phoenix_controller_pipeline/2
        (articles) lib/articles_web/endpoint.ex:1: ArticlesWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (articles) lib/articles_web/endpoint.ex:1: ArticlesWeb.Endpoint.plug_builder_call/2
```

**Comment by ankhers** [comment]
All of the results are just structs. Use `result.modified_count`, `result.matched_count`, etc instead.
