### ISSUE TITLE
No function clause matching Mongo.Protocol.handle_info({:DOWN, _,_,_,_}, _) 

### ISSUE THREAD

**Issue by jfcloutier** [elixir-mongo/mongodb#217]
This happened with v0.4.6:
```
GenServer #PID<0.2735.0> terminating
** (FunctionClauseError) no function clause matching in Mongo.Protocol.handle_info/2
    (mongodb) lib/mongo/protocol.ex:137: Mongo.Protocol.handle_info({:DOWN, #Reference<0.1604698500.2304245763.212217>, :process, #PID<0.21159.534>, :normal}, %{connect_timeout_ms: 5000, connection_type: :client, database: "bedrock", host: "10.136.9.241:27030", request_id: 12894048, socket: {:gen_tcp, #Port<0.5230>}, ssl: false, timeout: 50000, topology_pid: #PID<0.2729.0>, wire_version: 5, write_concern: %{w: 1}})
    (db_connection) lib/db_connection/connection.ex:584: DBConnection.Connection.do_handle_info/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.1604698500.2304245763.212217>, :process, #PID<0.21159.534>, :normal}
```

**Comment by ankhers** [comment]
I know it has been a while, but do you by chance know what happened when you received this down message? Have you had it since?

**Comment by jfcloutier** [comment]
I have no idea what caused the message, only that it happens infrequently. Sorry.

**Comment by ankhers** [comment]
Which version of db_connection does your application have loaded?

**Comment by jfcloutier** [comment]
@version "1.1.3"

**Comment by ankhers** [comment]
I just release version 0.5.0 that works with db_connection 2.x. I am closing this because it is now on an outdated version. If you continue having a similar problem on the latest version, please open a new ticket with the details.
