### ISSUE TITLE
no function clause matching in Mongo.Error.exception

### ISSUE THREAD

**Issue by tony612** [elixir-mongo/mongodb#287]
```
** (FunctionClauseError) no function clause matching in Mongo.Error.exception/1
    (mongodb) lib/mongo/error.ex:15: Mongo.Error.exception([tag: :tcp, action: "recv", reason: :timeout])
    (mongodb) lib/mongo/protocol/utils.ex:114: Mongo.Protocol.Utils.recv_error/2
    (mongodb) lib/mongo/protocol/utils.ex:13: Mongo.Protocol.Utils.message/3
    (mongodb) lib/mongo/protocol.ex:347: Mongo.Protocol.message_reply/2
    (mongodb) lib/mongo/protocol.ex:260: Mongo.Protocol.handle_execute/4
    (db_connection) lib/db_connection/holder.ex:277: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
```

**Comment by tschmittni** [comment]
Should be fixed: https://github.com/ankhers/mongodb/pull/283

@ankhers: could you release a new minor version?

**Comment by ankhers** [comment]
Pushing a new version right now.
