### ISSUE TITLE
error find with %BSON.Regex

### ISSUE THREAD

**Issue by codenoid** [elixir-mongo/mongodb#300]
syntax : 

```
Mongo.find(:pesantren, "pondok_pesantren", %{title: %BSON.Regex{pattern: "pocari"}}, limit: query_limit) |> Enum.to_list()
```
error log : 

```
[error] #PID<0.859.0> running Web.Endpoint (connection #PID<0.857.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /data/search?title=pocari&limit=25
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.iolist_size(["", 11, ["title", 0], [["pocari", 0], nil, 0]])
        (mongodb) lib/bson/encoder.ex:110: BSON.Encoder.document/1
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        (db_connection) lib/db_connection.ex:1161: DBConnection.maybe_encode/4
        (db_connection) lib/db_connection.ex:591: DBConnection.execute/4
        (mongodb) lib/mongo.ex:494: Mongo.raw_find/5
        (mongodb) lib/mongo/cursor.ex:46: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
        (elixir) lib/stream.ex:1377: anonymous fn/5 in Stream.resource/3
        (elixir) lib/enum.ex:3015: Enum.reverse/1
        (elixir) lib/enum.ex:2647: Enum.to_list/1
```

Info : 

```
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]   
                                                                                             
Elixir 1.8.2 (compiled with Erlang/OTP 20)                                                   
hex mongodb 0.5.1
```

**Comment by ankhers** [comment]
The `BSON.Regex` struct takes two parameters, `:pattern` and `:options`. Right now you are only specifying the one. If instead you change it to `%BSON.Regex{pattern: "pocari", options: ""}`, it should start working for you.

**Comment by codenoid** [comment]
first i try with `options`, error
without `options` still error

and i just realize, my gosh, the actual error are from Poison.encode, sorry
