### ISSUE TITLE
 Warnings: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor

### ISSUE THREAD

**Issue by fireproofsocks** [elixir-mongo/mongodb#334]
I'm getting a couple of these warnings when starting up `iex`:

```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.1) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.1) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.11.2) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.11.2) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.11.2) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.1) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.1) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.11.2) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.11.2) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.11.2) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
```

Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.1 (compiled with Erlang/OTP 22)

**Comment by joeapearson** [comment]
@fireproofsocks this should be fixed on `master`.

**Comment by scottmessinger** [comment]
@joeapearson can we close this issue? Or, are you waiting for a confirmation from @fireproofsocks?

**Comment by fireproofsocks** [comment]
Confirmed: this no longer appears on master.
