### ISSUE TITLE
BSON.ObjectId.decode!/1 is undefined or private

### ISSUE THREAD

**Issue by phalcondroid** [elixir-mongo/mongodb#82]
hi, is there a way to make BSON.ObjectId.decode!/1 available?, I'm passing a string as parameter

```
15:01:10.138 [error] #PID<0.287.0> running Estorage.Router terminated
Server: localhost:4001 (http)
Request: POST /uploadfile
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function BSON.ObjectId.decode!/1 is undefined or private
        (mongodb) BSON.ObjectId.decode!("579a2daf189fe3491028a3c6")
        (estorage) lib/estorage/users.ex:7: Estorage.Users.getById/1
        (estorage) lib/estorage/manager.ex:8: Estorage.Manager.upload_file/5
        (estorage) lib/estorage/router.ex:18: anonymous fn/1 in Estorage.Router.do_match/4
        (estorage) lib/estorage/router.ex:2: Estorage.Router.plug_builder_call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by ericmj** [comment]
It should be available. Are you using an older version?

**Comment by prasmussen** [comment]
I had the same problem using 0.1.1 from hex. I solved it by adding the following dependency which includes the decode function:
`{:mongodb, git: "https://github.com/ericmj/mongodb.git", tag: "3c481c086607d626b8cf9c8b8e5dc6fe2bc63dfd"}`
