### ISSUE TITLE
Error using Poolboy

### ISSUE THREAD

**Issue by bigardone** [elixir-mongo/mongodb#94]
Hi!
I'm trying to use the package in a project that I'm working on, but if I try to use `DBConnection.Poolboy` as specified in the instructions, I get the following error:

```
iex(11)> Mongo.find(:mongo, "products", %{}, limit: 20, pool: DBConnection.Poolboy) |> Enum.to_list
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
                    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:925: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:741: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1132: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
          (mongodb) lib/mongo.ex:386: Mongo.kill_cursors/3
           (elixir) lib/stream.ex:1129: Stream.do_resource/5
           (elixir) lib/enum.ex:1627: Enum.reduce/3
           (elixir) lib/enum.ex:2346: Enum.to_list/1
```

These are my deps:

```
* db_connection 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (db_connection) b2b88db6
  ok
* mongodb 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (mongodb) 95f85074
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
```

And this is how I have added the `Mongo` worker to the main supervision tree:

```elixir
defp children do
    [
        ...
        worker(Mongo, [mongo_config]),
        ...
    ]
  end

defp mongo_config do
    [
      name:     :mongo,
      pool:     DBConnection.Poolboy,
      username: System.get_env("MONGODB_USERNAME"),
      password: System.get_env("MONGODB_PASSWORD"),
      database: System.get_env("MONGODB_DBNAME"),
    ]
  end
```

The thing is that if I remove the pool from the config, and run the same query without the pool, it actually works. What might be going wrong?
Thanks in advance!

**Comment by ericmj** [comment]
Should be fixed in master. Can you try it?

**Comment by bigardone** [comment]
@ericmj working like a charm, thank you so much :)

**Comment by rawkode** [comment]
@ericmj  Can we get a tag with this fix?

**Comment by linjunpop** [comment]
The latest release(v0.2.0) does not include this fix.
